"""exp070b — predicate scan on REAL LADDER REPLAYS (not the local pool).

Why this supersedes the local scan (probe_predicates.py):
  exp070's local scan discovered that our pool's pure_wall opponent never plays
  its 4 Mega Kangaskhan ex -- so should_wall_mode's 0% fire rate there was an
  artifact of an unrepresentative opponent, not a pilot property. The local pool
  is contaminated on three axes at once (opponent pilot strength, archetype
  shares, reproduction fidelity). Real ladder replays have none of those
  problems: real opponents, real pilots, the real meta distribution, and the
  real W/L outcome -- at zero simulation cost.

Scope: replays generated by the KOFF builds only (v027/v028/v029). v025 and
earlier ran a different pilot, so their decision states say nothing about the
predicates in the shipped build.

Aggregation is TURN-LEVEL (exp022 rule: per-select counts multiply-count a turn).

IMPORTANT -- what this can and cannot conclude:
  A W/L split here is CORRELATIONAL. Reverse causation is very plausible (we are
  losing => more opposing ex pressure is on board => wall_mode fires). This scan
  chooses WHICH predicate deserves a counterfactual; it is not itself a verdict.
  Shipping still requires forced ON/OFF + the calibrated gate (0.7661).
"""
from __future__ import annotations
import os, sys, json, glob, collections

HERE = os.path.dirname(os.path.abspath(__file__))
WS = os.path.abspath(os.path.join(HERE, ".."))
ROOT = os.path.abspath(os.path.join(WS, ".."))
sys.path.insert(0, os.path.join(WS, "exp054_upperband"))
import eval_both_bands as EB
sys.path.insert(0, EB.CRN)
from harness_crn import load_engine
sys.path.insert(0, HERE)
import probe_predicates as PP

OUR_NAME = "Morita"
# koff builds only -- v025 and earlier ran a different pilot entirely
KOFF_DIRS = ["0718_54783479", "0718_54797761", "0719_54797761", "0720_54797761"]

PREDICATES = [
    "should_wall_mode",
    "should_ko_mode",
    "opponent_has_ex_or_ex_line_pressure",
    "opponent_can_attack_soon",
    "facing_lucario_strong",
    "active_tusk_ready",
    "can_bench_more",
    "opponent_has_trappable_bench",
]


def our_seats(info):
    names = info.get("TeamNames") or []
    return [i for i, n in enumerate(names) if OUR_NAME in str(n)]


def main():
    api, _ = load_engine()
    mod = PP.load_koff()
    to_obs = api.to_observation_class
    fns = {p: getattr(mod, p) for p in PREDICATES if callable(getattr(mod, p, None))}
    print(f"predicates found: {len(fns)}/{len(PREDICATES)}")

    # tally[pred][W|L] = {"turns": n, "fired": n}
    tally = collections.defaultdict(lambda: {"W": {"turns": 0, "fired": 0},
                                             "L": {"turns": 0, "fired": 0}})
    games = {"W": 0, "L": 0}
    opp_tally = collections.Counter()
    files = []
    for d in KOFF_DIRS:
        files += sorted(glob.glob(os.path.join(ROOT, "references/raw/replays", d,
                                               "episode-*-replay.json")))
    print(f"replay files: {len(files)}")

    for fp in files:
        try:
            d = json.load(open(fp))
        except Exception:
            continue
        info = d.get("info", {})
        seats = our_seats(info)
        if not seats:
            continue
        rewards = d.get("rewards") or []
        names = info.get("TeamNames") or []
        for seat in seats:
            if seat >= len(rewards) or rewards[seat] is None:
                continue
            won = rewards[seat] > (rewards[1 - seat] if len(rewards) > 1 else 0)
            k = "W" if won else "L"
            games[k] += 1
            if len(seats) == 1:
                opp_tally[str(names[1 - seat])] += 1
            seen_turns = set()
            for step in d.get("steps", []):
                if seat >= len(step):
                    continue
                ob = (step[seat] or {}).get("observation") or {}
                if not ob.get("current") or ob.get("select") is None:
                    continue
                try:
                    o = to_obs(ob)
                except Exception:
                    continue
                cur = o.current
                if cur is None or cur.yourIndex != seat:
                    continue
                t = cur.turn
                if t in seen_turns:      # TURN-LEVEL: one sample per turn
                    continue
                seen_turns.add(t)
                me = cur.players[seat]
                opp = cur.players[1 - seat]
                for pname, fn in fns.items():
                    try:
                        r = fn(opp) if fn.__code__.co_argcount == 1 else fn(me, opp, cur)
                    except Exception:
                        continue
                    tally[pname][k]["turns"] += 1
                    if r:
                        tally[pname][k]["fired"] += 1

    print(f"\ngames scanned: {games['W']}W-{games['L']}L "
          f"(wr {games['W']/max(1,games['W']+games['L']):.3f})")
    print(f"\n{'predicate':38s}{'fire% W':>10}{'fire% L':>10}{'turns/g':>10}   flag")
    out = {}
    for pname in PREDICATES:
        if pname not in tally:
            continue
        w, l = tally[pname]["W"], tally[pname]["L"]
        fw = 100 * w["fired"] / w["turns"] if w["turns"] else float("nan")
        fl = 100 * l["fired"] / l["turns"] if l["turns"] else float("nan")
        tg = (w["turns"] + l["turns"]) / max(1, games["W"] + games["L"])
        flag = ""
        if w["turns"] + l["turns"] and w["fired"] + l["fired"] == 0:
            flag = "NEVER FIRES in real games"
        elif w["turns"] and l["turns"] and abs(fw - fl) > 8:
            flag = f"W/L SPLIT {fl-fw:+.1f}pt in losses"
        out[pname] = {"fire_W": fw, "fire_L": fl, "turns_per_game": tg,
                      "W": w, "L": l}
        print(f"{pname:38s}{fw:10.1f}{fl:10.1f}{tg:10.1f}   {flag}")

    print(f"\ntop real opponents faced: {opp_tally.most_common(8)}")
    json.dump({"games": games, "predicates": out}, open(os.path.join(HERE, "replay_scan.json"), "w"), indent=1)


if __name__ == "__main__":
    main()
